[package]
name = "sanity_checks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sysinfo = "0.29.7"
tokio = "1.29.1"
